<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:simpleType name="markType">
        <xs:restriction base="xs:integer">
            <xs:minInclusive value="0"/>
            <xs:maxInclusive value="100"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="nonEmptyString">
        <xs:restriction base="xs:string">
            <xs:minLength value="1"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:element name="student">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="name" type="nonEmptyString"/>
                <xs:element name="roll" type="nonEmptyString"/>
                <xs:element name="marks">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="subject" minOccurs="5" maxOccurs="5">
                                <xs:complexType>
                                    <xs:simpleContent>
                                        <xs:extension base="markType">
                                            <xs:attribute name="name" type="nonEmptyString" use="required"/>
                                        </xs:extension>
                                    </xs:simpleContent>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

</xs:schema>
