services:
  web:
    image: shadoweternity/portdockerimage:latest
    ports:
      - "8080:80"
    volumes:
      - ./website:/usr/share/nginx/html
      - nginx_logs:/var/log/nginx         
volumes:
  nginx_logs:
